config/routes.rb
Rails.application.routes.draw do
  resources :group_categories
  resources :transaction_items
  resources :transaction_headers
  resources :categories do
    get 'account_groups', action: :account_groups
  end
  resources :groups
  resources :suppliers
  resources :account_users
  resources :accounts
  resources :welcomes
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'welcomes#index'
end

app/models/transaction_header.rb
class TransactionHeader < ApplicationRecord
  belongs_to :user
  belongs_to :account
  belongs_to :supplier
  has_many :transaction_items

  accepts_nested_attributes_for :transaction_items
end

app/controllers/transaction_headers_controller.rb
class TransactionHeadersController < ApplicationController
  before_action :set_transaction_header, only: [:show, :edit, :update, :destroy]
  before_action :form_dropdown_values, only: %i(new create edit)

  # GET /transaction_headers
  # GET /transaction_headers.json
  def index
    @transaction_headers = TransactionHeader.all
  end

  # GET /transaction_headers/1
  # GET /transaction_headers/1.json
  def show
    set_transaction_items
  end

  # GET /transaction_headers/new
  def new
    @transaction_header = TransactionHeader.new
    @transaction_header.transaction_items.build
  end

  # GET /transaction_headers/1/edit
  def edit
  end

  # POST /transaction_headers
  # POST /transaction_headers.json
  def create
    @transaction_header = TransactionHeader.new(transaction_header_params)
    respond_to do |format|
      if @transaction_header.save
        format.html { redirect_to @transaction_header, notice: 'Transaction header was successfully created.' }
        format.json { render :show, status: :created, location: @transaction_header }
      else
        format.html { render :new }
        format.json { render json: @transaction_header.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transaction_headers/1
  # PATCH/PUT /transaction_headers/1.json
  def update
    respond_to do |format|
      if @transaction_header.update(transaction_header_params)
        format.html { redirect_to @transaction_header, notice: 'Transaction header was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction_header }
      else
        format.html { render :edit }
        format.json { render json: @transaction_header.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transaction_headers/1
  # DELETE /transaction_headers/1.json
  def destroy
    @transaction_header.destroy
    respond_to do |format|
      format.html { redirect_to transaction_headers_url, notice: 'Transaction header was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_transaction_items
    @transaction_items = TransactionItem.where(transaction_header_id: @transaction_header.id)
  end

  def form_dropdown_values
    @users = User.where(id: current_user.id)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction_header
    @transaction_header = TransactionHeader.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def transaction_header_params
    params.require(:transaction_header).permit(:user_id, :transaction_date, :account_id, :supplier_id, :sign, :reconciled, :total, transaction_items_attributes: [:category_id, :amount, :description])
  end
end

app/helpers/transaction_headers_helper.rb
module TransactionHeadersHelper
end

app/views/transaction_headers/_form.html.erb
<%= form_with(model: transaction_header, local: true) do |form| %>
  <% if transaction_header.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction_header.errors.count, "error") %> prohibited this transaction_header from being saved:</h2>

      <ul>
      <% transaction_header.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select :id, @users, :id, :email %>
  </div>

  <div class="field">
    <%= form.label :transaction_date %>
    <%= form.date_select :transaction_date, id: :transaction_header_transaction_date %>
  </div>

  <div class="field">
    <%= form.label :account_id %>
    <%= form.text_field :account_id, id: :transaction_header_account_id %>
  </div>

  <div class="field">
    <%= form.label :supplier_id %>
    <%= form.text_field :supplier_id, id: :transaction_header_supplier_id %>
  </div>

  <div class="field">
    <%= form.label :sign %>
    <%= form.text_field :sign, id: :transaction_header_sign %>
  </div>

  <div class="field">
    <%= form.label :total %>
    <%= form.text_field :total, id: :transaction_header_total %>
  </div>
  <ul>
	<%= form.fields_for :transaction_items do |trans_form| %>
	<li>
  <div class="field">
    <%= form.label :category_id %>
    <%= trans_form.number_field :category_id %>
  </div>
    <div class="field">
    <%= form.label :amount %>
    <%= trans_form.number_field :amount %>
  </div>
    <div class="field">
    <%= form.label :description %>
    <%= trans_form.text_field :description %>
  </div>
 </li>
	<% end %>
	</ul>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transaction_headers/edit.html.erb
<h1>Editing Transaction Header</h1>

<%= render 'form', transaction_header: @transaction_header %>

<%= link_to 'Show', @transaction_header %> |
<%= link_to 'Back', transaction_headers_path %>

app/views/transaction_headers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transaction Headers</h1>

 <table class="table table-striped">
  <thead>
    <tr>
      <th>User</th>
      <th>Transaction date</th>
      <th>Account</th>
      <th>Supplier</th>
      <th>Sign</th>
      <th>Reconciled</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transaction_headers.each do |transaction_header| %>
      <tr>
        <td><%= transaction_header.user.email %></td>
        <td><%= transaction_header.transaction_date %></td>
        <td><%= transaction_header.account.name %></td>
        <td><%= transaction_header.supplier.name %></td>
        <td><%= transaction_header.sign %></td>
        <td><%= transaction_header.reconciled %></td>
        <td><%= transaction_header.total %></td>
        <td><%= link_to 'Show', transaction_header %></td>
        <td><%= link_to 'Edit', edit_transaction_header_path(transaction_header) %></td>
        <td><%= link_to 'Destroy', transaction_header, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction Header', new_transaction_header_path %>

app/views/transaction_headers/new.html.erb
<h1>New Transaction Header</h1>

<%= render 'form', transaction_header: @transaction_header %>

<%= link_to 'Back', transaction_headers_path %>

app/views/transaction_headers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @transaction_header.user.email %>
</p>

<p>
  <strong>Transaction date:</strong>
  <%= @transaction_header.transaction_date %>
</p>

<p>
  <strong>Account:</strong>
  <%= @transaction_header.account.name %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= @transaction_header.supplier.name %>
</p>

<p>
  <strong>Sign:</strong>
  <%= @transaction_header.sign %>
</p>

<p>
  <strong>Reconciled:</strong>
  <%= @transaction_header.reconciled %>
</p>

<p>
  <strong>Total:</strong>
  <%= @transaction_header.total %>
</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Category</th>
      <th>Amount</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transaction_items.each do |item| %>
      <tr>
        <td><%= Category.find(item.category_id).name %></td>
        <td><%= item.amount %></td>
        <td><%= item.description %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_transaction_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Edit', edit_transaction_header_path(@transaction_header) %> |
<%= link_to 'Back', transaction_headers_path %>