config/routes.rb
Rails.application.routes.draw do
  resources :group_categories
  resources :transaction_items
  resources :transaction_headers
  resources :categories do
    get 'account_groups', action: :account_groups
  end
  resources :groups
  resources :suppliers
  resources :account_users
  resources :accounts
  resources :welcomes
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'welcomes#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    can :read, Account, id: account_users(user)
    can :destroy, Account
    can :create, Account
  end
  def account_users(user)
    user.account_users.map(&:account_id)
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :account_users
  has_many :transaction_headers

    def self.accounts_for(account_ids)
      accounts = Account.where(id: account_ids)
      accounts.sort_by{|e| e[:id]}
    end

    def self.accounts_for_user(user_id)
      account_users = AccountUser.where(user_id: user_id);
      # require 'pry'
      # binding.pry
      Account.where(user_id: user_id)
    end
end

app/models/account_user.rb
class AccountUser < ApplicationRecord
  belongs_to :account
  belongs_to :user

  def self.account_users_for(user_id)
    AccountUser.where(user: user_id)
  end

  def self.accounts_for(user_id)
    accounts_for_user = Account.where(id: account_users.map(&:id))
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :account

  def self.for_account(account_id)
    Category.where(account_id: account_id)
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :account

  def self.groups_for(account_id)
    Group.where(account_id: account_id)
  end
end

app/models/group_category.rb
class GroupCategory < ApplicationRecord
  belongs_to :category
  belongs_to :group
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :account
end

app/models/transaction_header.rb
class TransactionHeader < ApplicationRecord
  belongs_to :user
  belongs_to :account
  belongs_to :supplier
  has_many :transaction_items

  accepts_nested_attributes_for :transaction_items
end

app/models/transaction_item.rb
class TransactionItem < ApplicationRecord
  belongs_to :category
  belongs_to :transaction_header
end

app/models/user.rb
class User < ApplicationRecord
  has_many :account_users
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  load_and_authorize_resource
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.accounts_for_user(current_user.id)
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    set_transactions
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)
    @account.user_id = current_user.id
    respond_to do |format|
      if @account.save
        au = AccountUser.new(user_id: current_user.id, account_id: @account.id)
        au.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_transactions
    @transactions = TransactionHeader.where(account_id: @account.id)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_account
    @account = Account.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def account_params
    params.require(:account).permit(:name, :account_type)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :form_dropdown_values, only: %i(new create edit)
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def form_dropdown_values
    @user_accounts ||= Account.accounts_for([current_user.id])
    @users = [current_user]
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def group_params
    params.require(:group).permit(:name, :description, :account_id)
  end
end

app/helpers/account_users_helper.rb
module AccountUsersHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #71da71;">
      <a class="navbar-brand" href="#">Budget</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href=<%= accounts_path %>>Accounts <span class="sr-only">(current)</span></a>
          </li>
            <li class="nav-item">
            <a class="nav-link" href=<%= account_users_path %>>Account Users</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href=<%= transaction_headers_path %>>Transactions</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href=<%= suppliers_path %>>Suppliers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href=<%= groups_path %>>Groups</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href=<%= categories_path %>>Categories</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href=<%= group_categories_path %>>Grouped Categories</a>
          </li>
          <% if current_user %>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Sign out (#{current_user.first_name} #{current_user.surname})", destroy_user_session_path, method: :delete %></a>
          </li>
          <%else%>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Sign in", new_user_session_path %></a>
          </li>
          <%end%>
        </ul>
      </div>
    </nav>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>